### ISSUE TITLE
Wii U Render: disabling vSync causes vertex corruption

### ISSUE THREAD

**Issue by ds-sloth** [devkitPro/SDL#77]
### What's the issue you encountered?

This is another issue we found while testing recent TheXTech engine (https://github.com/TheXTech/TheXTech) builds on Wii U.

When we tested a branch with in-game configuration support that calls `SDL_RenderSetVSync(renderer, g_config.render_vsync);` on our Wii U target, we found substantial vertex corruption that appears only when that call in included. (Note that the default value for vSync is disabled.)

Later I found that the devkitPro SDL2 renderer for Wii U forces vSync to be enabled on render initialization (likely due to this issue). However, it still exposes the `SDL_RenderSetVSync` method (added in SDL 2.0.18).

We worked around the issue by forcing vSync to always be on on Wii U. This is not ideal because our game engine runs at 65 FPS for historical reasons.

### How can the issue be reproduced?

This issue can be trivially reproduced by calling `SDL_RenderSetVSync(renderer, 0);` after initializing an SDL2 renderer on Wii U.

### Environment?

Duplicated from my other report regarding Wii U:
> I'm using Fedora, but this also affects our CI builds which pull from your Docker image. I really don't think that the environment is related.

### Additional context?

I tried to create a fix that waited for a buffer flip instead of for a vSync by removing the condition `if (renderer->info.flags & SDL_RENDERER_PRESENTVSYNC)` from `WIIU_SDL_RenderPresent` and instead making the Vsync call depend on the flag as shown below, but this reduced performance, so we used the workaround explained above.

```c++
        wait_count++;

        if (renderer->info.flags & SDL_RENDERER_PRESENTVSYNC) {
            GX2WaitForVsync();
        }
        else {
            GX2WaitForFlip();
        }
    }
```

Thanks for your time and hard work on the library!

**Comment by GaryOderNichts** [comment]
The vertex corruption is caused by the CPU writing to the attribute buffers, while the GPU is still drawing them to the current frame.
The current V-Sync code waits for the previous frame to be drawn before moving on, which is why enabling V-Sync is necessary.
I'm currently working on some renderer changes which should hopefully address this.

**Comment by ds-sloth** [comment]
It's great to hear you've got some render improvements in the pipeline. In that case I might suggest that you temporarily paper over this bug by defining a stubbed implementation of `SDL_RenderSetVSync`.

**Comment by GaryOderNichts** [comment]
I pushed my rendering changes to the `wiiu-sdl2-2.28-renderer-improvements` branch. Can you test if this fixes the problems you described without reducing performance?

**Comment by ds-sloth** [comment]
On Cemu, I can't get the game to render more than 60FPS even with vSync disabled. On the plus side, the game keeps good performance and doesn't create the vertex corruption we were observing earlier, so I think your fix is a success on that front.

Perhaps @Wohlstand can test on his hardware. (Wohlstand, you'd need to remove the `__WIIU__`-specific code disabling the vSync option in `render_sdl.cpp` and `config.h`.)

**Comment by GaryOderNichts** [comment]
I can confirm that your engine runs at 65 fps on hardware. Note that this will cause some screen tearing and I do not recommend disabling vSync.

**Comment by Wohlstand** [comment]
The 65 is the expected framerate of the game (because the original author who made the engine for Windows and wrote on VB6, attempted to work around the Windows's GDI to render game in sync as I guess, but this is a "bear service" that makes a pain). And in order to preserve real-time accuracy of original game, it runs ~65 FPS, and the special code adjusts the framerate of the game when v-sync is off.

**Comment by ds-sloth** [comment]
> Note that this will cause some screen tearing and I do not recommend disabling vSync.

I totally understand this. We have a lot of platforms and some are more graceful than others when vsync gets disabled. But it's important for us to provide the option for compatibility reasons. Thanks a lot for your help with this!

I'll leave this issue open until Wohlstand has tested on hardware as well.

**Comment by Wohlstand** [comment]
I'll try to test now, just I should locally tweak the code as you said first. And... which SDL2 build I should do? Just the manually built top of current devkitPro SDL?

**Comment by ds-sloth** [comment]
Thank you! Please build SDL2 from Gary's current Wii U render improvements branch of this repository. And be sure to disable all Wii U-specific render macros (in config.h and render_sdl.cpp).

**Comment by Wohlstand** [comment]
I finally tested the thing, and, on REAL hardware it leads the mess with vertexes when V-Sync is disabled, but when it's enabled - everything goes just fine:

https://github.com/user-attachments/assets/6d23c2a8-211f-4209-9889-f4175d4da6db

(The video is captued using HDMI video capture device)

**Comment by GaryOderNichts** [comment]
It works correctly for me on hardware, please make sure you're using the correct branch and did a clean rebuild of SDL and your project.

https://github.com/user-attachments/assets/4143bbd4-ff82-4ac8-9629-689a2d7e4cfb

**Comment by Wohlstand** [comment]
Sounds like the default SDL2 from packages got been linked even headers are correct... I'll try to uninstall the packet and try rebuild and re-run the thing...

**Comment by WinterMute** [comment]
> Sounds like the default SDL2 from packages got been linked even headers are correct... I'll try to uninstall the packet and try rebuild and re-run the thing...

Try this ``sudo dkp-pacman -U https://pkg.devkitpro.org/packages/test/wiiu-sdl2-2.28.5-2-any.pkg.tar.zst``

If it's windows then remove `sudo dkp-` if it's arch or something with native pacman then remove `dkp-`

**Comment by Wohlstand** [comment]
> If it's windows

You may don't worry:
- I am Linux guy since 2014. :)
- On Windows, my game won't build because of the way how CMake generates invalid makefiles for external projects because it incorrectly interpret paths mixed with Windows native and MSyS's. So, in my manuals I tell to Windows users to build via WSL or via Linux VM.

> Try this 

Uno momento...

**Comment by WinterMute** [comment]
> * On Windows, my game won't build because of the way how CMake generates invalid makefiles for external projects because it incorrectly interpret paths mixed with Windows native and MSyS's. So, in my manuals I tell to Windows users to build via WSL or via Linux VM.

It should work fine if you run msys2 native cmake via msys2 shell - pacman -S cmake

**Comment by Wohlstand** [comment]
Huh, let me try this then... If it will work, then I'll update manual to note about this.

**Comment by Wohlstand** [comment]
Okay, I found the problem of the issue: it was my local mess:
- I though my custom build of SDL2 went into one directory
- But actually, the install prefix was wrong (default one instead of my custom)
- My local build linked to wrong SDL2 version which is way older than needed

Now trying with the correct SDL2 build, and:
IT WORKS!

https://github.com/user-attachments/assets/850be4cc-5af9-44fd-bb75-bbc49d148d13

**Comment by Wohlstand** [comment]
> It should work fine if you run msys2 native cmake via msys2 shell - pacman -S cmake

I did what you said, but it still fails, and the reason:
![2024-09-08_02-00-54](https://github.com/user-attachments/assets/6889dd20-cbc4-4852-afaf-8d3f11d25108)

Anyway, this problem is off-topic here, and, can you suggest me the repo where I can properly report it?

**Comment by WinterMute** [comment]
> Anyway, this problem is off-topic here, and, can you suggest me the repo where I can properly report it?

Better off in the forums at https://devkitpro.org if you can. It's more of a general build system issue than anything we have a specific repo for.

**Comment by Wohlstand** [comment]
About the forum: my problem still didn't solved, because my main mailbox won't be allowed by thing, and I can't catch any notifications immediately because of that. Is possible to make an exception to bypass that check? You can check two of my last PM at the forum to see my explanations, the check was being a subnet based and it's pretty paranoid check.

**Comment by ds-sloth** [comment]
Thanks for your hard work on this, Gary, and for your help with the build, WinterMute.
